version: "3"
services:
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb:27017
    ports:
      - "8000:8000"
    links:
      - mongodb
    